# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0008_auto_20170926_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorite_Quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorite_Quote',
            field=models.ManyToManyField(related_name='user_favorited', to='belt.User'),
        ),
    ]
